name: ulid4d
description: Universally Unique Lexicographically Sortable Identifier for Dart
version: 2.0.0
homepage: https://github.com/Aallam/ulid4d
repository: https://github.com/Aallam/ulid4d
issue_tracker: https://github.com/Aallam/ulid4d/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  meta: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.2.0
  collection: ^1.16.0
  lints: ^2.0.0
  test: ^1.16.0
  uuid: ^3.0.6
