name: ulid4d
description: Universally Unique Lexicographically Sortable Identifier for Dart
version: 1.1.0
homepage: https://github.com/Aallam/ulid4d/tree/main

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  collection: ^1.16.0
  lints: ^2.0.0
  test: ^1.16.0
